apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joannedada/React-java-app.git
    targetRevision: HEAD
    path: charts/backend
    helm:
      values: |
        image:
          repository: joannedada/backend
          tag: "1.0.3"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true