replicaCount: 2
image:
  repository: joannedada/backend
  tag: "1.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  # Domain-less configuration
  paths:
    - path: /api
      pathType: Prefix